apiVersion: v1
kind: Pod
metadata:
  name: spring-build-ci
  labels:
    app: spring-build-ci
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.6.0-debug
      imagePullPolicy: Always
      env:
        - name: container
          value: docker
      command: ["sleep"]
      args: ["99d"]
      volumeMounts:
        - name: jenkins-docker-cfg
          mountPath: /kaniko/.docker

    - name: maven
      image: maven:alpine
      command: ["cat"]
      tty: true
      volumeMounts:
        - name: m2
          mountPath: /root/.m2/

    - name: docker-tools
      image: rmkanda/docker-tools:latest
      command: ["cat"]
      tty: true
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run
        - name: trivycache
          mountPath: /tmp/trivycache/

    - name: trufflehog
      image: rmkanda/trufflehog
