apiVersion: v1
kind: Pod
metadata:
  name: spring-build-ci                  # ✅ Required
  labels:
    app: spring-build-ci
spec:
  containers:
    - name: maven
      image: maven:alpine
      command: ["cat"]
      tty: true
      volumeMounts:
        - name: m2
          mountPath: /root/.m2/

    - name: docker-tools
      image: rmkanda/docker-tools:latest
      command: ["cat"]
      tty: true
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run
        - name: trivycache
          mountPath: /tmp/trivycache/

    - name: trufflehog
      image: rmkanda/trufflehog
      command: ["cat"]
      tty: true

    - name: licensefinder
      image: licensefinder/license_finder
      command: ["cat"]
      tty: true

  volumes:
    - name: m2
      emptyDir: {}                       # ✅ Portable alternative to hostPath

    - name: docker-sock
      hostPath:
        path: /var/run                   # ⚠️ Still okay if you're using hostPath for Docker socket access

    - name: trivycache
      emptyDir: {}                       # ✅ In-memory, ephemeral cache; avoids node dependency

